name: Deploy 11ty to Google Cloud Bucket

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build 11ty site
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: List build directory contents
        run: ls -la _site

      - name:
        id: "upload-file"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "/_site/index.html"
          destination: "gs://${{ secrets.BUCKET_NAME }}"

      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: _site
          destination: "gs://${{ secrets.BUCKET_NAME }}"

      - name: Set public access
        run: "gsutil iam ch allUsers:objectViewer gs://${{ secrets.BUCKET_NAME }}"
